#!/bin/sh
# Sandbox profile warm-up: pre-warm the SAME profile the extension uses
# (/tmp/google_search_profile) by visiting the Google homepage and a
# search page with the real headful Chrome on a live Xvfb display.
# Cookies minted here (NID, AEC, ...) come from the sandbox's own egress
# IP, so the profile no longer looks like a brand-new, cookie-less client
# on a known-good IP. Run this, THEN run the pi -p forceBrowser test.
# Zero dollar-signs in the payload (paste-safe).
pkill Xvfb; pkill -f google-chrome; sleep 0.5; rm -f /tmp/.X11-unix/X99 /tmp/.X99-lock; node -e "const {spawn}=require('child_process');const fs=require('fs');function runChrome(url){return new Promise((resolve)=>{const ch=spawn('google-chrome',['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-first-run','--no-default-browser-check','--user-data-dir=/tmp/google_search_profile','--dump-dom',url],{env:{...process.env,DISPLAY:':99',TZ:'Europe/Berlin'},stdio:'ignore'});let done=false;const finish=(code)=>{if(done)return;done=true;try{ch.kill('SIGKILL')}catch(e){};resolve(code)};ch.on('close',(c)=>finish(c));ch.on('error',()=>finish('spawn-error'));setTimeout(()=>finish('timeout'),40000)});}async function main(){const xvfb=spawn('Xvfb',[':99','-screen','0','1920x1080x24','-nolisten','tcp'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,1500));if(fs.existsSync('/tmp/.X11-unix/X99')===false){console.log('XVFB-DIED');process.exit(1)};console.log('xvfb up');console.log('warming homepage...');const r1=await runChrome('https://www.google.com/');console.log('homepage run:',r1);console.log('warming search...');const r2=await runChrome('https://www.google.com/search?q=test&hl=en');console.log('search run:',r2);try{const ck=fs.readFileSync('/tmp/google_search_profile/Default/Cookies','latin1');for(const name of ['NID','AEC','CONSENT','__oglb']){console.log('cookie',name,':',ck.includes(name)?'present':'missing')}}catch(e){console.log('cookies file:',e.message)}xvfb.kill();process.exit(0)}main().catch(e=>{console.log('ERROR:',e.message);process.exit(3)});"
